SRCS:=only-wwmath-example/wwmath.cpp only-wwmath-example/main.cpp
OPTS=-municode -msse2 -static-libgcc  -D_WINDOWS -fpermissive
INCS=-I./Generals/Code/Libraries/Source/WWVegas/ -I./Generals/Code/Libraries/Source/WWVegas/WWDebug/ -I./Generals/Code/Libraries/Source/WWVegas/WWLib/ -I./Generals/Code/Tools/WW3D/ -I./Generals/Code/Libraries/Source/WWVegas/WWMath/ -I./Generals/Code/GameEngine/Include/ -I./Generals/Code/Libraries/Source/WWVegas/WWLib/ -I./Generals/Code/Tools/WW3D/pluglib/ -I./Generals/Code/GameEngine/Include/Common/ -I./Generals/Code/Libraries/Include/ -I./lib/stlport/ -I./lib/stlport/stlport/

all:
	i686-w64-mingw32-g++-win32 -save-temps -w -s -nostdlib ${OPTS} ${INCS} -I/usr/share/mingw-w64/include ${SRCS} -o ww3d2.o  -Wl,-nostdlib,-lkernel32

