all:
	i686-w64-mingw32-g++-win32 -o main.exe \
\
-municode -msse2 -static-libgcc -static-libstdc++ \
\
-I. \
-I../lib/directx8/include \
-I../lib/directx-math/Inc \
-I../lib/directx-dxut/ \
-I../lib/directx-dxut/Core \
-I../lib/directx-dxut/Optional \
\
../lib/directx-dxut/Core/DXUT.cpp \
../lib/directx-dxut/Core/DXUTmisc.cpp \
../lib/directx-dxut/Core/DXUTDevice11.cpp \
../lib/directx-dxut/Optional/DXUTsettingsdlg.cpp \
../lib/directx-dxut/Optional/SDKmisc.cpp \
../lib/directx-dxut/Optional/DXUTgui.cpp \
../lib/directx-dxut/Optional/SDKmesh.cpp \
../lib/directx-dxut/Optional/DXUTcamera.cpp \
../lib/directx-dxut/Core/ScreenGrab.cpp \
../lib/directx-dxut/Core/DDSTextureLoader.cpp \
../lib/directx-dxut/Core/WICTextureLoader.cpp \
../lib/directx-dxut/Optional/DXUTres.cpp \
\
/usr/i686-w64-mingw32/lib/libd3dcompiler.a \
/usr/i686-w64-mingw32/lib/libusp10.a \
/usr/i686-w64-mingw32/lib/libwindowsapp.a \
/usr/i686-w64-mingw32/lib/libcomctl32.a \
/usr/i686-w64-mingw32/lib/libgdi32.a \
/usr/i686-w64-mingw32/lib/libdxerr9.a \
\
-L../lib/directx8/lib \
\
BasicHLSL11.cpp
